# SPDX-FileCopyrightText: Copyright Contributors to the ORT Container project
#
# SPDX-License-Identifier: Apache-2.0

name: Containerize
on:
  schedule:
    - cron: '22 11 * * *'  # Trigger daily at 11:22 UTC'
  workflow_dispatch: # allow manual triggering
  push:

env:
  REGISTRY: ghcr.io

jobs:
  containerize:
    strategy:
      fail-fast: false
      matrix:
        include:
            # NOTE: for a PR use 'refs/pull/<pr-nr>/merge' as ref
          - ref: main
            suffix: ''
            description: 'Main branch'
            image_url: 'https://github.com/oss-review-toolkit/ort'
          - ref: 'refs/pull/6053/merge'
            suffix: '-pr-6053'
            description: 'docker: Build and run as a non-privileged user'
            image_url: 'https://github.com/oss-review-toolkit/ort/pull/6053'
          - ref: 'refs/pull/6075/merge'
            suffix: '-pr-6075'
            description: 'docker: Prepare base layer to non privileged user'
            image_url: 'https://github.com/oss-review-toolkit/ort/pull/6075'
    name: containerize
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest ORT repo
        uses: actions/checkout@v3
        with:
          repository: oss-review-toolkit/ort
          ref: ${{ matrix.ref }}

      - name: Inspect result
        run: ls -la

      - name: Store repo SHA in variable
        run: echo "ORT_SHA=$(/usr/bin/git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Lowercase image name based on repo
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}${{ matrix.suffix }}" >> ${GITHUB_ENV}

      - name: Shorten repo SHA
        run: echo "REPO_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Store date in variable
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=builder-sha-${{ env.REPO_SHA }}
            type=raw,value=date-${{ env.DATE }}
            type=raw,value=ort-sha-${{ env.ORT_SHA }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=ort-containers.image.title="${{ github.event.repository.name }}"
            ort.opencontainers.image.description="A temporary solution to provide a ORT Container."
            org.opencontainers.image.url="${{ matrix.image_url }}"
            org.opencontainers.image.source="${{ matrix.image_url }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: List image digests
        run: docker images --digests

      - name: Push Docker image
        # Only push on main branch
        if: github.ref == 'refs/heads/main'
        run: docker image push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
